### ISSUE TITLE
emojione is not defined

### ISSUE THREAD

**Issue by Morronic** [braune-digital/ckeditor-emojione#3]
I am attempting to integrate emojione with my ckeditor. I went to http://ckeditor.com/builder and chose Office 2013 theme. I then downloaded emojione and extracted it to the plugins folder of ckeditor. I then added config.extraPlugins = "emojione"; and when I navigate to the webpage with ckeditor I get a "Uncaught ReferenceError: emojione is not defined emojione.js:98"

I have cleared my browser cache and tried a different browser, all report the same thing.
Has anyone had this issue yet?

**Comment by hbraune** [comment]
Please have a look at the readme: https://github.com/braune-digital/ckeditor-emojione It is necessary to install and include the emojione library into your project. We are going to publish a new version of the plugin which will check for availability and otherwise include the library.

**Comment by Morronic** [comment]
Either i'm not understanding or you're not reading I apologize for the mix up but as I stated above I did include the emojione library into my project with the emojione library included in the plugins folder. Is there something else I need after that?

**Comment by EdanBrooke** [comment]
I am having this issue.

**Comment by hbraune** [comment]
We´ve released the version 1.0.2 minutes ago, which solves the problem with using the builder.

**Comment by carlosmirandalevy** [comment]
I have the same issue.
It is indeed not defined.

**Comment by SFSailor** [comment]
I also have this issue.  I am using it in a Drupal installation.  Or trying to...

**Comment by dougmorin** [comment]
@SFSailor I'm having the same issue integrating into a Drupal 8 site. Did you find a fix for it?

**Comment by Morronic** [comment]
It was patched a couple weeks after I posted this. If it’s back I might try an older version.

**Comment by SFSailor** [comment]
> @SFSailor I'm having the same issue integrating into a Drupal 8 site. Did you find a fix for it?

I did not find a fix.  To be honest, I do not even remember why I wanted this!

**Comment by dougmorin** [comment]
I'd like to comment here because I figured out what the problem is, and i'm assuming most others have had this problem too.

If you download the plugin right from the ckeditor site, you're missing the 'lib' folder that IS included if you download the plugin right from this github repo.  I replaced what I had from the ckeditor site with this github repo and it worked.  I then noticed the lib folder was the only thing missing.

just a heads up in case anyone else is still trying to use this.

**Comment by Tectract** [comment]
Uncaught ReferenceError: emojione is not defined

Just got this problem, Nov 2019. I'm using the latest master. Is something wrong?

emojione/lib/js/emojione.js

Where do I get this file? It's not in this repo.

Hmmmmmm, I found a version here, and it does impart partial functionality to the emojione plugin, but I think it's the wrong version... No emojis :(

https://github.com/joypixels/emojione/blob/master/lib/js/emojione.js

Maybe I can figure out the right version to use, somewhere... Here's a clue in emojione.min.js

    /*! emojione 02-12-2016 */

notes: I tried installing emojione via npm, and including it via application.js, same result, now I'm getting this error:

Uncaught TypeError: Cannot read property 'focus' of null
    at emojione.js?t=FB9E:165

It's failing here, I don't know why or what exactly this line of code is trying to do, set focus it appears, on an element it can't find...

var firstSmile = self.getElement().getElementsByTag( 'a' ).getItem( 0 );
					firstSmile.focus();


I tried 

        "emojione": "~2.0.0",

in package.json. No difference. Using old versions of emojione.js doesn't seem to solve the problem.

**Comment by Tectract** [comment]
It appears the problem was partially this line:

emojione.imagePathSVGSprites = '/vendor/emojione/assets/sprites/emojione.sprites.svg';

was pointing to nothing on my system. Pointing it at this file in my node_modules/ subfolder instead of vendor/ folder did NOT solve the issue. It appears to be loading the plugin, but not ANY of the icons. 

adding a debug statement in the dialog/emojione.js file here:

		for (var shortcode in emojione.emojioneList) {

			if (!emojione.emojioneList.hasOwnProperty(shortcode)) continue;
			var obj = emojione.emojioneList[shortcode];
			if (!obj.isCanonical) continue;
			for (var prop in obj) {
				if(!obj.hasOwnProperty(prop)) continue;
				if (config.emojione.emojis[group].indexOf(shortcode) != -1) {
					list[shortcode] = obj;
				}
			}
		}

    console.log("adding shortcodes of length " + Object.keys(list).length + " from list");

shows "adding shortcodes of length 0 from list", five times. No icons are being loaded. Any ideas to fix?
